services:
  - type: web
    name: nixcard
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: BASE_URL
        value: https://nixcard.onrender.com
      - key: DATABASE_URL
        value: sqlite:///nixcard.db
